
# Command messages to server
P1_ASSIGN = "CLIENT_ASSIGNED_PLAYER_ONE"
P2_ASSIGN = "CLIENT_ASSIGNED_PLAYER_TWO"

P1_SPACE = "PLAYER_ONE_SPACE"

P2_SPACE = "PLAYER_TWO_SPACE"

F1_RM = "FOOD_ONE_REMOVE"
F2_RM = "FOOD_TWO_REMOVE"

DROP = "DROP"

D_MSG = "CLIENT_DISCONNECTED"
